repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        description: "Format Python code with black"
        entry: black
        language: system
        types: [python]
        exclude: '^$'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
